name: Create snap action
run-name: ${{ github.actor }} is creating testing snap
on: [push]
jobs:
  Create-Snap-Action:
    runs-on: ubuntu-22.04
    continue-on-error: true
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Installation Step
        run: |
          echo "Install snapcraft"
          sudo apt update
          sudo apt install snapcraft
          echo "Install snapcraft"
          sudo snap install lxd
          echo "Initialize snapcraft"
          sudo lxd init --auto
      - name: Run snapcraft
        run: | 
          cd tests
          # run snapcraft in destructive mode 
          # -- network doesn't work properly otherwise
          sudo snapcraft --destructive-mode
      - name: Output logs
        if: always()
        run: |
          journalctl -u snap.multipass.multipassd
          sudo bash -c 'cat /root/.local/state/snapcraft/log/snapcraft*.log'
