name: Create snap action
run-name: ${{ github.actor }} is creating testing snap
on: [push]
jobs:
  Create-Snap-Action:
    runs-on: ubuntu-24.04
    continue-on-error: true
    steps:
      - name: Check out repository code step
        uses: actions/checkout@v4
      - name: Installation step
        run: |
          sudo snap install snapcraft --classic
          sudo snap install lxd
          sudo lxd init --auto
          sudo lxd waitready
      - name: Run snapcraft step
        run: | 
          cd tests
          # run snapcraft in destructive mode 
          # -- network doesn't work properly otherwise
          sudo snapcraft --destructive
      - name: Output logs step
        if: always()
        run: |
          journalctl -u snap.lxd.daemon
          sudo bash -c 'cat /root/.local/state/snapcraft/log/snapcraft*.log'
